version: "3"

services:
    frontend:
        image: minpeter/frontend
        build: ./frontend
        ports:
            - 80:80

    backend:
        image: minpeter/backend
        build: ./backend
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - database

    database:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todolist
            MYSQL_USER: minpeter
            MYSQL_PASSWORD: 1234
        ports:
            - 3306:3306
