version: "3.0"

services:
    database:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todolist
            MYSQL_USER: minpeter
            MYSQL_PASSWORD: 1234
        ports:
            - 3306:3306
    backend:
       build: .
       restart: on-failure
       ports:
           - 8080:8080
       depends_on:
           - database