spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: minpeter
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    databse-platform: org.hibernate.dialect.MySQL5nnoDBDialect
    properties:
      hibernate:
        show_sql: yes
        format_sql: yes
        user_sql_comments: yes