spring:
  datasource:
    url: jdbc:mariadb://database:3306/todolist
    username: minpeter
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    databse-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        show_sql: yes
        format_sql: yes
        user_sql_comments: yes